services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: apache
    ports:
      - "8080:80"
    volumes:
      - ./site:/var/www/html/site
    depends_on:
      - db
      - node

  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    ports:
      - "3366:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    env_file:
      - .env
    depends_on:
      - db
  
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site:/app/site

volumes:
  db_data:
    driver: local
